### ISSUE TITLE
travis: many build don't work for me

### ISSUE THREAD

**Issue by jpcaruana** [japaric/rust-everywhere#39]
Hi, 

I tried to build a helloworld using rust-everywhere, but I can't make it work at all: Many build fail, some succeed (not always the same) : see https://travis-ci.org/jpcaruana/rust-build-test

The most frequent error is about not found files in `target` directory.

```
cannot open `target/i686-unknown-linux-gnu/debug/hello' (No such file or directory)
cp: target/x86_64-apple-darwin/release/hello: No such file or directory
```

What am I doing wrong ?
Thanks.

**Comment by japaric** [comment]
Hey Jean,

The problem here is that the name of your project is `helloworld` so the binaries generated by Cargo have the name `helloworld`. As you can see here:

> cp: target/x86_64-apple-darwin/release/hello

The rust-everywhere template is using `hello` as the name of the binaries. You'll have to rename all the references to `hello` with `helloworld`.

**Comment by jpcaruana** [comment]
Hi,
sorry for the noise : I missed these TODOs in the templates. It now works perfectyl (of course) : https://github.com/jpcaruana/rust-build-test/releases/tag/v0.0.3
