### ISSUE TITLE
Add an example for allow_failures:

### ISSUE THREAD

**Issue by dns2utf8** [japaric/rust-everywhere#44]
I would like to run the tests on arm64 but I do not care if they fail.
I am not sure how to configure my [.travis.yml](https://github.com/dns2utf8/lasttest/blob/master/.travis.yml) file.

Can you help me or give a working example?

**Comment by japaric** [comment]
> Can you help me or give a working example?

Sure, I can give you some pointers.

The allowed_failures syntax looks like [this](https://github.com/japaric/rust-everywhere/commit/edf474ae0fe0d0db77a201fa477de2aa12c50f88#diff-354f30a63fb0907d4ad57269548329e3L89).

arm64 is a little more elaborated than the existing targets because it can't run on Ubuntu Precise (glibc is too old, no support for arm64 in that version) so you need to use Ubuntu Trusty instead. Look at [rust-cross](https://github.com/japaric/rust-cross) for guidance. In particular, this is the [Trusty bit](https://github.com/japaric/rust-cross/blob/bdb08bc0dc7360dc7265b9901bf22ada99ef0e8a/.travis.yml#L6-L8) and these are [the apt packages](https://github.com/japaric/rust-cross/blob/bdb08bc0dc7360dc7265b9901bf22ada99ef0e8a/ci/install.sh#L6-L7) you need to install.

I'll push a working example to this repository later today.

**Comment by dns2utf8** [comment]
Thank you
